language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: ocux99P6M36P7XyfEB9+UFV6uZLgdeTEXk8JNJyIFOpvEikSmfWxOIbw1n52EaJC3iIlhXN+PGdS76N1jz9KPc0n0SOOKl+mmWRWVhJ+CFF9z8+nWhdlc+JRJdkjOZGbNI/duW7rU0t4o73xwsHzrBIMgiKZvTSW0i4kJV5GCsW9BLPXnHJm+ZmrxKGXVERIy13svkXBkCkK1vRA/36b5AR6HWvLhs9NW4RhDG2oC5UzqNxRCALqmIgR7l8BeuK32OC6ggNZ70qusBbACZoKiZf5KhJVKJbKc+Sk1G87isvnkvwKGxTcHw5yusKSRsQtuveI4CmBWoJsfQZIlCz6v6K9y8crSdBc3ANrwXE+W/ko8VgppZZBR6Y3oN4cqdnbrKuPqM7/XabpI1u/a2mQmW7kYizPMeu7/5R0sYm6NFAxYBxAX3a+0P+YMRIVl6SlgWoggtWO693KQs3106Zd+S8Ecb3HiaoB8OQy3JHI6chazxzILmGXUCG62JLgPzv+YhGAKKD+cT1nPuyMc6wjdJPWZyjJLC2smhzVfEYk4TwMQHOiGU9md+xM+f/Be3hUtuSFAEYldNT8ZTSzA1lomzNgasdtHZ2BtLo4CfxFkF25dy9QXhy54GpTvR6Q4m0ibq7U/j7lwCdxyea6VJihOp1FimMR6kmefLkYiKNE0A4=
  app: aqueous-waters-22959
  on:
    repo: ddigiulio/books-api
