language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: EvmhXnKysCqUgn9cHZ6QeYFFFdmZEI7hKPt46YiZDofKKvMO7OjNRVz6iB8NEPPNmKmhzrOvinj8lYnLMMrvGMmMbOBT9BSFsulB0OZZvkpuhUtcKySBucHOc2nr0Wo+68LVg79kNGeFpe/2/urSN3QtCZlqQoMVuC0aQbSwMUL2C57P1Lwzz0BIZm2/pR+dmb1nwIDwWyBhYnyqJhCv51zcfpSyqE7ruvGLBy7IGT3cAFN2nnSwvngeDMHD8OB4uLWbhsgbnG2du8xzSibprlVs0NXwId1TlpuO7Cyu3PloU4zDh99MLGj0yV0xgBLatbI5dXnmXAdlDPrWwXr4ebDjVbNzNDhC/3O45VZKkvACmDgehR7KCvWEJUp+eE7mBBDjOYGSO0NUORVu43VU63bi8UR1D0VL7tBs+QBvsZW9zA0oTPXTsjI+OE16YbvPtFu6NpKWPs15MhO7hmu0BjuMAJmyrzJVbAjE87EqXbuOEWQ6NtnHuQfE2nlgNpXRvmsCcWiqN/mtleG963rlyGvTvt6w4crmm03XH2/6KZwe1IuLmzDSX7reY/krOpdfisTIpZPpg0Fh7bBtJoikf28Tf28K3FFPqWJh5tXooZjJXw/bi4ImKec7pfInrlLqPuj0HXhDGj3tByjnbzppjNay/u1E8X+Jl0ttAQyEDKg=
  app: sleepy-bayou-48369
  on:
    repo: ddigiulio/books-api
